#################################
# Port Number
#################################
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#################################
# Banner Setting
#################################
spring:
  banner:
    location: banner/banner.txt

  application:
    name: JpaStudy

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

#################################
# MySQL Setting
#################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpastudy?serverTimezone=UTC
    username: root
    password: 1234

  #################################
  # JPA Setting
  #################################
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false

###############################
# Log info
###############################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace